### ISSUE TITLE
Add TLS Support

### ISSUE THREAD

**Issue by SckyzO** [treydock/infiniband_exporter#24]
Hello, 

Thank you for your work. 

Is it possible to add  basic authentication and TLS support over web.config-file ?

**Comment by treydock** [comment]
This was released as 0.10.0-rc.0.  I don't run exporters with TLS or basic auth so please let me know if this RC release works for what you need and I'll release 0.10.0.

**Comment by SckyzO** [comment]
Perfect :) Thank you. I wait your final release. 

You can add this to your README.md : 

## TLS and basic auth

`infiniband_exporter` supports TLS and basic auth using [exporter-toolkit](https://github.com/prometheus/exporter-toolkit). To use TLS and/or basic auth, users need to use `--web.config.file` CLI flag as follows

```
infiniband_exporter --web.config.file=web-config.yaml
```

A sample `web-config.yaml` file can be fetched from [exporter-toolkit repository](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-config.yml). The reference of the `web-config.yaml` file can be consulted in the [docs](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md).
