### ISSUE TITLE
mad_rpc_open_port: client_register for mgmt 1 failed

### ISSUE THREAD

**Issue by xuchenhui-5** [treydock/infiniband_exporter#26]
Hi，
I encountered an error message when I exec "ibnetdiscover" or perfquery in command. So, I can't profile metrics by this exporter. Can you help me ?

thanks.

error log:
[root@test-k8snode-32-43 1]# ibnetdiscover
ibwarn: [298726] mad_rpc_open_port: client_register for mgmt 1 failed
/var/tmp/OFED_topdir/BUILD/rdma-core-2307mlnx47/libibnetdisc/ibnetdisc.c:802; can't open MAD port ((null):0)
ibnetdiscover: iberror: failed: discover failed
[root@test-k8snode-32-43 1]# perfquery
ibwarn: [299010] mad_rpc_open_port: client_register for mgmt 1 failed
perfquery: iberror: failed: Failed to open '(null)' port '0'

ibstatus is ok:
[root@test-k8snode-32-43 1]# ibstatus
Infiniband device 'mlx5_0' port 1 status:
        default gid:     fe80:0000:0000:0000:966d:aeff:feb3:832e
        base lid:        0x0
        sm lid:          0x0
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            400 Gb/sec (4X NDR)
        link_layer:      Ethernet

Infiniband device 'mlx5_1' port 1 status:
        default gid:     fe80:0000:0000:0000:966d:aeff:feec:c6a0
        base lid:        0x0
        sm lid:          0x0
        state:           4: ACTIVE
        phys state:      5: LinkUp
        rate:            400 Gb/sec (4X NDR)
        link_layer:      Ethernet

**Comment by treydock** [comment]
The IB devices appear to be configured as Ethernet and not Infiniband.  I can replicate the same errors on some of my systems where I've configured the Mellanox cards to do only Ethernet and not Infiniband.  When a device is setup as Ethernet it won't be able to communicate to the IB fabric in a way that's required by things like ibnetdiscover and perfquery.

**Comment by xuchenhui-5** [comment]
thanks
